/*
FORMULARIO PARA REGISTRO DE ESTUDIANTES
 */
package com.mycompany.proyecto_asistencia;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.StringTokenizer;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ALBARO CALLIZAYA MOLLO
 */
public final class FORM_ASISTENCIA extends javax.swing.JFrame {
  //ALBARO CALLIZAYA MOLLO
private String dirArchivo="archiEstudiantes.txt";
ESTUDIANTE est;// DECLARA UN OBJETO est EN LA CLASE ESTUDIANE
VECTOR_ESTUDIANTES ve=new VECTOR_ESTUDIANTES();
// declara un objeto ve de la clase VECTOR_ESTUDIANTES
    DefaultTableModel dtm=new DefaultTableModel();
    int clickTabla;
    public FORM_ASISTENCIA() {
        initComponents();
        this.setLocationRelativeTo(this);
        dtm.addColumn("RU");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellidos");
        dtm.addColumn("Genero");
        dtm.addColumn("Edad");
        dtm.addColumn("Estado civil");//    dhfvbfhbvibuycvsdbv
        dtm.addColumn("Celular");
        dtm.addColumn("Nacionalidad");
        dtm.addColumn("Cargo");
        this.tablaEstudiantes.setModel(dtm);
        try{
        cargarArchivoEstudiante();
        listarEstudiantes();
        }catch(Exception ex){
        mensaje("ERROR AL ABRIR EL ARCHIVO DE ESTUDIANTES!!");
        };
    }        //ALBARO CALLIZAYA MOLLO
    public void cargarArchivoEstudiante()
    {
       File archi=new File(dirArchivo); 
       
       if(!archi.exists())
           try{
               archi.createNewFile();
           } catch(IOException ex){
               Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(Level.SEVERE,null,ex);
           }
       else{
       try{
           FileReader frest=new FileReader(dirArchivo);
           BufferedReader br=new BufferedReader(frest);
           String linea=null;
           //llevamos los daatos del archivo al vector
           linea=br.readLine();
           while(linea!=null)
           {
               //separar la cadena linea separado por el token
               StringTokenizer st=new StringTokenizer(linea,",");
               
               est=new ESTUDIANTE();
               int cod=Integer.parseInt(st.nextToken());
               est.setRU(cod);
               est.setNombre(st.nextToken());
               est.setApellido(st.nextToken());
               est.setGenero(st.nextToken().charAt(0));
               est.setEdad(cod);
               est.setEstadoCivil(st.nextToken());
               est.setCelular(cod);
               est.setNacionalidad(st.nextToken());
               est.setCargo(st.nextToken());
               ve.agregarEstudiante(est);
               linea=br.readLine();
           }
           br.close();
       }catch(Exception ex)
       {
           mensaje("ERROR AL CARGAR EL ARCHIVO!!!"+ex.getMessage());
       }
    }}         //ALBARO CALLIZAYA MOLLO
    public void listarEstudiantes()
    {
        Object fila[]=new Object[dtm.getColumnCount()];
        
        for(int i=0; i<ve.cantidadEstudiante();i++)
        {
            est=ve.obtenerEstudiante(i);
            fila[0]=est.getRU();
            fila[1]=est.getNombre();
            fila[2]=est.getApellido();
            fila[3]=est.getGenero();
            fila[4]=est.getEdad();
            fila[5]=est.getEstadoCivil();
            fila[6]=est.getCelular();
            fila[7]=est.getNacionalidad();
            fila[8]=est.getCargo();
            dtm.addRow(fila);
        }
        tablaEstudiantes.setModel(dtm);
    }
void mensaje(String msje)
    {
        JOptionPane.showMessageDialog(null,msje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENERO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brMasculino = new javax.swing.JRadioButton();
        brFemenino = new javax.swing.JRadioButton();
        txtRU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIngreo = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        EDAD = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtEstadoCivil = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO 3ER SEMESTRE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE SUPERVISOR");

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RU", "NOMBRE", "APELLIDO", "GENERO", "EDAD", "ESTADO CIVIL", "CELULAR", "NACIONALIDAD", "CARGO"
            }
        ));
        tablaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);

        btnGuardar.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel3.setText("C I :");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel4.setText("NOMBRE:");

        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel5.setText("APELLIDO:");

        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel6.setText("GENERO:");

        brMasculino.setBackground(new java.awt.Color(255, 255, 255));
        GENERO.add(brMasculino);
        brMasculino.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        brMasculino.setText("MASCULINO");

        brFemenino.setBackground(new java.awt.Color(255, 255, 255));
        GENERO.add(brFemenino);
        brFemenino.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        brFemenino.setText("FEMENINO");

        btnModificar.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIngreo.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnIngreo.setText("REGISTRAR INGRESO");
        btnIngreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreoActionPerformed(evt);
            }
        });

        btnSalida.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnSalida.setText("REGISTRAR SALIDA");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        EDAD.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        EDAD.setText("EDAD:");

        jLabel8.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel8.setText("ESTADO CIVIL:");

        jLabel9.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel9.setText("CELULAR:");

        jLabel10.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel10.setText("NACIONALIDAD:");

        jLabel11.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel11.setText("CARGO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EDAD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(btnIngreo))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel6))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(brMasculino)
                                                .addGap(18, 18, 18)
                                                .addComponent(brFemenino))
                                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(115, 115, 115)
                                                .addComponent(btnSalida)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtRU, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEliminar, btnGuardar, btnModificar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIngreo, btnSalida});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EDAD)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminar)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnModificar)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(brMasculino)
                                        .addComponent(brFemenino))
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnGuardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalida)
                            .addComponent(btnIngreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int leerRU()
        {
            try{
                String aux=txtRU.getText();
                int RU=Integer.parseInt(aux);
                return RU;
            }catch(Exception e){
                return -99;
            }
        }
        String leerNombre()
        {
            try{
                String nombre=txtNombre.getText().trim();
                return nombre;
            }catch(Exception e){
                return null;
            }     //ALBARO CALLIZAYA MOLLO
        }
        String leerApellido()
        {
            try{
                String apellidos=txtApellido.getText().trim();
                return apellidos;
            }catch(Exception e){
                return null;
            }
        }
        int leerEdad()
        {
            try{
                String aux=txtEdad.getText();
                int edad=Integer.parseInt(aux);
                return edad;
            }catch(Exception e){
                return -99;
            }
        }
        String leerEstadoCivil()
        {
            try{
                String estadoCivil=txtEstadoCivil.getText().trim();
                return estadoCivil;
            }catch(Exception e){
                return null;
            }
        }
        int leerCelular()
        {
            try{
                String aux=txtCelular.getText();
                int celular=Integer.parseInt(aux);
                return celular;
            }catch(Exception e){
                return -99;
            }
        }
        String leerNacionalidad()
        {
            try{
                String nacionalidad=txtNacionalidad.getText().trim();
                return nacionalidad;
            }catch(Exception e){
                return null;
            }
        }
        String leerCargo()
        {
            try{
                String cargo=txtCargo.getText().trim();
                return cargo;
            }catch(Exception e){
                return null;
            }
        }
        
        
        
        
        void registrarEstudiante(File dirArchivo)
        {
            try{
                if(leerRU()==99) mensaje("DEBE INGRESAR UN NUMERO ENTERO");
                else if(leerNombre()==null)mensaje("INGRESE EL NOMBRE");
                else if(leerApellido()==null)mensaje("INGRESE EL APELLIDO");
                else if(leerEdad()==99)mensaje("INGRESE LA EDAD");
                else if(leerEstadoCivil()==null)mensaje("INGRESE SU ESTADO CIVIL");
                else if(leerCelular()==99)mensaje("INGRESE SU CELULAR");
                else if(leerNacionalidad()==null)mensaje("INGRESE SU NACIONALIDAD");
                else if(leerCargo()==null)mensaje("INGRESE SU CARGO");
                {
                    char genero;
                    if(brMasculino.isSelected())
                        genero='M';
                    else genero='F';
                    
                    est=new ESTUDIANTE(leerRU(), leerNombre(), leerApellido(),genero, leerEdad(), leerEstadoCivil(), leerCelular(), leerNacionalidad(), leerCargo());
                    if((ve.buscarRUEstudiante(est.getRU()))!=-1)
                    {
                        mensaje("ESTE CODIGO YA EXISTE");
                    }
                    else{
                        ve.agregarEstudiante(est);
                    }
                    grabarEstudiante();
                    limpiar();
                    listarEstudiantes();
                }
            }catch(Exception ex)
            {
                mensaje("ERROR AL ABRIR EL ARCHIVO");
            }
        }
        void grabarEstudiante() throws IOException// implementado sin saber
        {
            FileWriter fw;
            PrintWriter pw;
            try{            //ALBARO CALLIZAYA MOLLO
                fw=new FileWriter(dirArchivo);
                pw=new PrintWriter(fw);
                for(int i=0;i<ve.cantidadEstudiante();i++)
                {
                    est=ve.obtenerEstudiante(i);
                    pw.println(String.valueOf(est.getRU())+", "+est.getNombre()+
                    ", "+est.getApellido()+", "+
                            est.getGenero()+", "+est.getEdad()+
                            ", "+est.getEstadoCivil()+", "+est.getCelular()+
                            ", "+est.getNacionalidad()+", "+est.getCargo());
                }
                pw.close();
            }
            catch(Exception ex)
            {
                mensaje("ERROR AL GRABAR EL ARCHIVO");
            }
        }
        void limpiar()
        {
            limpiarTabla();
            txtRU.setText(null);
            txtNombre.setText(null);
            txtApellido.setText(null);
            brMasculino.setSelected(true);
            txtEdad.setText(null);
            txtEstadoCivil.setText(null);
            txtCelular.setText(null);
            txtNacionalidad.setText(null);
            txtCargo.setText(null);
            limpiarTabla();
        }
        void limpiarTabla()
        {
            for(int i=0; i<tablaEstudiantes.getRowCount();i++){
                dtm.removeRow(i);
                i-=1;
            }
        }       //ALBARO CALLIZAYA MOLLO
        char leerGenero()
        {
            if(brMasculino.isSelected())
                return 'M';
            else return 'F';
        }
        void modificarEstudiante(File dirArch)
        {
            try{
                if(leerRU()==99)mensaje("INGRESAR RU ENTERO");
                else if(leerNombre()==null)mensaje("INGRESE EL NOMBRE");
                else if(leerApellido()==null)mensaje("INGRESAR APELLIDOS");
                else if(leerEdad()==99)mensaje("INGRESE LA EDAD");
                else if(leerEstadoCivil()==null)mensaje("INGRESE SU ESTADO CIVIL");
                else if(leerCelular()==99)mensaje("INGRESE SU CELULAR");
                else if(leerNacionalidad()==null)mensaje("INGRESE SU NACIONALIDAD");
                else if(leerCargo()==null)mensaje("INGRESE SU CARGO");
                {
                    int RU=ve.buscarRUEstudiante(leerRU());
                    est=new ESTUDIANTE(leerRU(),leerNombre(),leerApellido(),leerGenero(), leerEdad(), leerEstadoCivil(), leerCelular(), leerNacionalidad(), leerCargo());
                    if(RU==-1)
                        ve.agregarEstudiante(est);
                    else{
                        ve.modificarEstudiante(RU, est);
                    }
                    grabarEstudiante();
                    limpiar();
                    listarEstudiantes();
                } 
            }catch(Exception ex){
                mensaje("ERROR AL ABRIR EL ARCHIVO PARA MODIFICAR");
            }
        }
        void eliminarEstudiante()
        {        //ALBARO CALLIZAYA MOLLO
            try
            {
                if(leerRU()==-99)mensaje("INGRESAR UN RU ENTERO");
                else
                {
                    int RU=ve.buscarRUEstudiante(leerRU());
                    if(RU==-1)
                    {
                        mensaje("RU NO EXISTENTE");
                    }else{
                        int s=JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE "
                        +"ELIMINAR ESTE ESTUDIANTE?","SI/NO",0);
                        if(s==0)
                        {
                            ve.eliminarEstudiante(RU);
                            grabarEstudiante();
                            limpiar();
                            listarEstudiantes();
                        }      //ALBARO CALLIZAYA MOLLO
                    }
                    
                }
            }catch(Exception ex){
                mensaje ("NO SE PUDO ELIMINAR A ESTE ESTUDIANTE");
            }
        }
        
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
File dirarchi=new File(dirArchivo);
this.registrarEstudiante(dirarchi);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        File archi=new File(dirArchivo);
        modificarEstudiante(archi);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarEstudiante();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiantesMouseClicked
        clickTabla=tablaEstudiantes.rowAtPoint(evt.getPoint());
        
        int RU =(int) tablaEstudiantes.getValueAt(clickTabla, 0);
        String nombre="" + tablaEstudiantes.getValueAt(clickTabla, 1);
        String apellido="" + tablaEstudiantes.getValueAt(clickTabla, 2);
        char genero=(char)tablaEstudiantes.getValueAt(clickTabla, 3);
        int edad =(int) tablaEstudiantes.getValueAt(clickTabla, 4);
        String estadoCivil="" + tablaEstudiantes.getValueAt(clickTabla, 5);
        int celular =(int) tablaEstudiantes.getValueAt(clickTabla, 6);
        String nacionalidad="" + tablaEstudiantes.getValueAt(clickTabla, 7);
        String cargo="" + tablaEstudiantes.getValueAt(clickTabla, 8);
        
        txtRU.setText(String.valueOf(RU));
        txtNombre.setText((nombre));
        txtApellido.setText(apellido);
        if(genero=='M')brMasculino.setSelected(true);
        else brFemenino.setSelected(true);
        txtEdad.setText(String.valueOf(edad));
        txtEstadoCivil.setText((estadoCivil));
        txtCelular.setText(String.valueOf(celular));
        txtNacionalidad.setText((nacionalidad));
        txtCargo.setText((cargo));
    }//GEN-LAST:event_tablaEstudiantesMouseClicked

    private void btnIngreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreoActionPerformed
        FORM_INGRESO fp=new FORM_INGRESO();
        this.dispose();       //ALBARO CALLIZAYA MOLLO
        fp.setVisible(true);
    }//GEN-LAST:event_btnIngreoActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        FORM_SALIDA fp=new FORM_SALIDA();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_btnSalidaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_ASISTENCIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EDAD;
    private javax.swing.ButtonGroup GENERO;
    private javax.swing.JRadioButton brFemenino;
    private javax.swing.JRadioButton brMasculino;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngreo;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRU;
    // End of variables declaration//GEN-END:variables
}
