/*
FORMULARIO PARA REGISTRO DE ESTUDIANTES
 */
package com.mycompany.proyecto_asistencia;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.StringTokenizer;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ALBARO CALLIZAYA MOLLO
 */
public final class FORM_ASISTENCIA extends javax.swing.JFrame {
  //ALBARO CALLIZAYA MOLLO
private String dirArchivo="archiEstudiantes.txt";
ESTUDIANTE est;// DECLARA UN OBJETO est EN LA CLASE ESTUDIANE
VECTOR_ESTUDIANTES ve=new VECTOR_ESTUDIANTES();
// declara un objeto ve de la clase VECTOR_ESTUDIANTES
    DefaultTableModel dtm=new DefaultTableModel();
    int clickTabla;
    public FORM_ASISTENCIA() {
        initComponents();
        this.setLocationRelativeTo(this);
        dtm.addColumn("RU");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellidos");
        dtm.addColumn("Genero");
        this.tablaEstudiantes.setModel(dtm);
        try{
        cargarArchivoEstudiante();
        listarEstudiantes();
        }catch(Exception ex){
        mensaje("ERROR AL ABRIR EL ARCHIVO DE ESTUDIANTES!!");
        };
    }        //ALBARO CALLIZAYA MOLLO
    public void cargarArchivoEstudiante()
    {
       File archi=new File(dirArchivo); 
       
       if(!archi.exists())
           try{
               archi.createNewFile();
           } catch(IOException ex){
               Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(Level.SEVERE,null,ex);
           }
       else{
       try{
           FileReader frest=new FileReader(dirArchivo);
           BufferedReader br=new BufferedReader(frest);
           String linea=null;
           //llevamos los daatos del archivo al vector
           linea=br.readLine();
           while(linea!=null)
           {
               //separar la cadena linea separado por el token
               StringTokenizer st=new StringTokenizer(linea,",");
               est=new ESTUDIANTE();
               int cod=Integer.parseInt(st.nextToken());
               est.setRU(cod);
               est.setNombre(st.nextToken());
               est.setApellido(st.nextToken());
               est.setGenero(st.nextToken().charAt(0));
               ve.agregarEstudiante(est);
               linea=br.readLine();
           }
           br.close();
       }catch(Exception ex)
       {
           mensaje("ERROR AL CARGAR EL ARCHIVO!!!"+ex.getMessage());
       }
    }}         //ALBARO CALLIZAYA MOLLO
    public void listarEstudiantes()
    {
        Object fila[]=new Object[dtm.getColumnCount()];
        
        for(int i=0; i<ve.cantidadEstudiante();i++)
        {
            est=ve.obtenerEstudiante(i);
            fila[0]=est.getRU();
            fila[1]=est.getNombre();
            fila[2]=est.getApellido();
            fila[3]=est.getGenero();
            dtm.addRow(fila);
        }
        tablaEstudiantes.setModel(dtm);
    }
void mensaje(String msje)
    {
        JOptionPane.showMessageDialog(null,msje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENERO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brMasculino = new javax.swing.JRadioButton();
        brFemenino = new javax.swing.JRadioButton();
        txtRU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIngreo = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO 3ER SEMESTRE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMD\\Pictures\\sal.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel2.setText("ASISTENCIA DE ESTUDIANTES");

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RU", "NOMBRE", "APELLIDO", "GENERO"
            }
        ));
        tablaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);

        btnGuardar.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel3.setText("RU:");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel4.setText("NOMBRE:");

        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel5.setText("APELLIDO:");

        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        jLabel6.setText("GENERO:");

        brMasculino.setBackground(new java.awt.Color(255, 255, 255));
        GENERO.add(brMasculino);
        brMasculino.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        brMasculino.setText("MASCULINO");

        brFemenino.setBackground(new java.awt.Color(255, 255, 255));
        GENERO.add(brFemenino);
        brFemenino.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        brFemenino.setText("FEMENINO");

        btnModificar.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIngreo.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnIngreo.setText("REGISTRAR INGRESO");
        btnIngreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreoActionPerformed(evt);
            }
        });

        btnSalida.setFont(new java.awt.Font("Eras Light ITC", 1, 13)); // NOI18N
        btnSalida.setText("REGISTRAR SALIDA");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)))
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRU, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnModificar)
                                    .addComponent(btnEliminar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(brMasculino)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnSalida))
                                    .addComponent(brFemenino)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngreo)
                        .addGap(194, 194, 194)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEliminar, btnGuardar, btnModificar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIngreo, btnSalida});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(brMasculino)
                    .addComponent(brFemenino))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngreo)
                    .addComponent(btnSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int leerRU()
        {
            try{
                String aux=txtRU.getText();
                int RU=Integer.parseInt(aux);
                return RU;
            }catch(Exception e){
                return -99;
            }
        }
        String leerNombre()
        {
            try{
                String nombre=txtNombre.getText().trim();
                return nombre;
            }catch(Exception e){
                return null;
            }     //ALBARO CALLIZAYA MOLLO
        }
        String leerApellido()
        {
            try{
                String apellidos=txtApellido.getText().trim();
                return apellidos;
            }catch(Exception e){
                return null;
            }
        } 
        void registrarEstudiante(File dirArchivo)
        {
            try{
                if(leerRU()==99) mensaje("DEBE INGRESAR UN NUMERO ENTERO");
                else if(leerNombre()==null)mensaje("INGRESE EL NOMBRE");
                else if(leerApellido()==null)mensaje("INGRESE EL APELLIDO");
                else
                {
                    char genero;
                    if(brMasculino.isSelected())
                        genero='M';
                    else genero='F';
                    
                    est=new ESTUDIANTE(leerRU(), leerNombre(), leerApellido(),genero);
                    if((ve.buscarRUEstudiante(est.getRU()))!=-1)
                    {
                        mensaje("ESTE CODIGO YA EXISTE");
                    }
                    else{
                        ve.agregarEstudiante(est);
                    }
                    grabarEstudiante();
                    limpiar();
                    listarEstudiantes();
                }
            }catch(Exception ex)
            {
                mensaje("ERROR AL ABRIR EL ARCHIVO");
            }
        }
        void grabarEstudiante() throws IOException// implementado sin saber
        {
            FileWriter fw;
            PrintWriter pw;
            try{            //ALBARO CALLIZAYA MOLLO
                fw=new FileWriter(dirArchivo);
                pw=new PrintWriter(fw);
                for(int i=0;i<ve.cantidadEstudiante();i++)
                {
                    est=ve.obtenerEstudiante(i);
                    pw.println(String.valueOf(est.getRU())+", "+est.getNombre()+
                    ", "+est.getApellido()+", "+
                            est.getGenero());
                }
                pw.close();
            }
            catch(Exception ex)
            {
                mensaje("ERROR AL GRABAR EL ARCHIVO");
            }
        }
        void limpiar()
        {
            limpiarTabla();
            txtRU.setText(null);
            txtNombre.setText(null);
            txtApellido.setText(null);
            brMasculino.setSelected(true);
            limpiarTabla();
        }
        void limpiarTabla()
        {
            for(int i=0; i<tablaEstudiantes.getRowCount();i++){
                dtm.removeRow(i);
                i-=1;
            }
        }       //ALBARO CALLIZAYA MOLLO
        char leerGenero()
        {
            if(brMasculino.isSelected())
                return 'M';
            else return 'F';
        }
        void modificarEstudiante(File dirArch)
        {
            try{
                if(leerRU()==99)mensaje("INGRESAR RU ENTERO");
                else if(leerNombre()==null)mensaje("INGRESE EL NOMBRE");
                else if(leerApellido()==null)mensaje("INGRESAR APELLIDOS");
                else 
                {
                    int RU=ve.buscarRUEstudiante(leerRU());
                    est=new ESTUDIANTE(leerRU(),leerNombre(),leerApellido(),leerGenero());
                    if(RU==-1)
                        ve.agregarEstudiante(est);
                    else{
                        ve.modificarEstudiante(RU, est);
                    }
                    grabarEstudiante();
                    limpiar();
                    listarEstudiantes();
                } 
            }catch(Exception ex){
                mensaje("ERROR AL ABRIR EL ARCHIVO PARA MODIFICAR");
            }
        }
        void eliminarEstudiante()
        {        //ALBARO CALLIZAYA MOLLO
            try
            {
                if(leerRU()==-99)mensaje("INGRESAR UN RU ENTERO");
                else
                {
                    int RU=ve.buscarRUEstudiante(leerRU());
                    if(RU==-1)
                    {
                        mensaje("RU NO EXISTENTE");
                    }else{
                        int s=JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE "
                        +"ELIMINAR ESTE ESTUDIANTE?","SI/NO",0);
                        if(s==0)
                        {
                            ve.eliminarEstudiante(RU);
                            grabarEstudiante();
                            limpiar();
                            listarEstudiantes();
                        }      //ALBARO CALLIZAYA MOLLO
                    }
                    
                }
            }catch(Exception ex){
                mensaje ("NO SE PUDO ELIMINAR A ESTE ESTUDIANTE");
            }
        }
        
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
File dirarchi=new File(dirArchivo);
this.registrarEstudiante(dirarchi);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        File archi=new File(dirArchivo);
        modificarEstudiante(archi);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarEstudiante();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiantesMouseClicked
        clickTabla=tablaEstudiantes.rowAtPoint(evt.getPoint());
        
        int RU =(int) tablaEstudiantes.getValueAt(clickTabla, 0);
        String nombre="" + tablaEstudiantes.getValueAt(clickTabla, 1);
        String apellido="" + tablaEstudiantes.getValueAt(clickTabla, 2);
        char genero=(char)tablaEstudiantes.getValueAt(clickTabla, 3);
        
        txtRU.setText(String.valueOf(RU));
        txtNombre.setText((nombre));
        txtApellido.setText(apellido);
        if(genero=='M')brMasculino.setSelected(true);
        else brFemenino.setSelected(true);
    }//GEN-LAST:event_tablaEstudiantesMouseClicked

    private void btnIngreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreoActionPerformed
        FORM_INGRESO fp=new FORM_INGRESO();
        this.dispose();       //ALBARO CALLIZAYA MOLLO
        fp.setVisible(true);
    }//GEN-LAST:event_btnIngreoActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        FORM_SALIDA fp=new FORM_SALIDA();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_btnSalidaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_ASISTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_ASISTENCIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GENERO;
    private javax.swing.JRadioButton brFemenino;
    private javax.swing.JRadioButton brMasculino;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngreo;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRU;
    // End of variables declaration//GEN-END:variables
}
